### PR TITLE
Fix Annotations

### PR DESCRIPTION
**Pull request by Cyborgmas**
Also, some inputs can be both zips or directories, so instead I make the input be a string instead for the file name.

If the tag could be updated as well, that would be nice.

### CODE REVIEW

**Comment by LexManos** [comment]
1) This should probably be upstreamed
2) Perhaps the better idea would be to migrate to two tasks to get around the issue. OR could have two inputs `inputFile` `inputDir` that are both @Optional.

**Comment by zml2008** [comment]
Would a FileCollection or `final ConfigurableFileCollection` (used with `project.zipTree`/`ArchiveOperations.zipTree`) work instead? Concern there would probably be if that hurts performance from having Gradle try to snapshot a large input tree.

**Comment by LexManos** [comment]
The problem with zipTree is that last time I looked into that, Gradle implements that by simply extracting the zip to a temp directory and treating it as a directory. Which defeats the entire point.

**Comment by Cyborgmas** [comment]
upstreamed https://github.com/CadixDev/ProPatcher/pull/13

**Pull request closed without merging**
